"""Plant photographs for `seed_premium_plants`.

Every URL is a Wikimedia Commons file served through `Special:FilePath`, which
redirects to a 1000px rendition of the original — freely licensed, and stable
in a way a search-engine result URL is not. Each one was fetched and confirmed
to answer with an image before being written here.
"""

PHOTOS: dict[str, str] = {
    'Money Plant (Pothos)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Money_Plant_%28Epipremnum_aureum%29_4.jpg?width=1000',
    'Snake Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg?width=1000',
    'Jade Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Crassula_ovata_700.jpg?width=1000',
    'ZZ Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamioculcas_zamiifolia_1.jpg?width=1000',
    'Peace Lily': 'https://commons.wikimedia.org/wiki/Special:FilePath/Spathiphyllum_cochlearispathum_RTBG.jpg?width=1000',
    'Monstera Deliciosa': 'https://commons.wikimedia.org/wiki/Special:FilePath/Monstera_deliciosa2.jpg?width=1000',
    'Areca Palm': 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%95%A3%E5%B0%BE%E8%91%B5Dypsis_lutescens_20210511145013_05.jpg?width=1000',
    'Aglaonema (Chinese Evergreen)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Aglaonema_commutatum2.jpg?width=1000',
    'Spider Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Hierbabuena_0611_Revised.jpg?width=1000',
    'Lucky Bamboo': 'https://commons.wikimedia.org/wiki/Special:FilePath/Dracaena_sanderiana_2.jpg?width=1000',
    'Fittonia (Nerve Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Colpfl25.jpg?width=1000',
    'Calathea': 'https://commons.wikimedia.org/wiki/Special:FilePath/Starr_080716-9470_Calathea_crotalifera.jpg?width=1000',
    'Syngonium (Arrowhead Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Zingiber_malaysianum.jpg?width=1000',
    'Boston Fern': 'https://commons.wikimedia.org/wiki/Special:FilePath/Boston_Fern_%282873392811%29.png?width=1000',
    'Aloe Vera': 'https://commons.wikimedia.org/wiki/Special:FilePath/Aloe_vera_flower_inset.png?width=1000',
    'Rubber Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Ficus_elastica_leaves_02.JPG?width=1000',
    'Fiddle Leaf Fig': 'https://commons.wikimedia.org/wiki/Special:FilePath/Starr_031108-0130_Ficus_lyrata.jpg?width=1000',
    'Cast Iron Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Aspidistra_elatior1.jpg?width=1000',
    'Philodendron': 'https://commons.wikimedia.org/wiki/Special:FilePath/Philodendron_giganteum_-_Laeken_Royal_Greenhouses_-_Royal_Castle_of_Laeken_-_Brussels%2C_Belgium_-_DSC07236.jpg?width=1000',
    'Anthurium': 'https://commons.wikimedia.org/wiki/Special:FilePath/Anthurium3.JPG?width=1000',
    'Hibiscus': 'https://commons.wikimedia.org/wiki/Special:FilePath/Hibiscus_Brilliant.jpg?width=1000',
    'Rose': 'https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_rubiginosa_1.jpg?width=1000',
    'Jasmine': 'https://commons.wikimedia.org/wiki/Special:FilePath/Arabian_jasmin%2C_Tunisia_2010.jpg?width=1000',
    'Bougainvillea': 'https://commons.wikimedia.org/wiki/Special:FilePath/Bougainvillea_closeup.jpg?width=1000',
    'Periwinkle (Vinca)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vinca_%28Catharanthus_roseus%29_cultivada_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55231652268.jpg?width=1000',
    'Croton': 'https://commons.wikimedia.org/wiki/Special:FilePath/Colpfl05.jpg?width=1000',
    'Plumeria (Frangipani)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Plumeria_rubra-4.JPG?width=1000',
    'Oleander': 'https://commons.wikimedia.org/wiki/Special:FilePath/Nerium_oleander_flowers_leaves.jpg?width=1000',
    'Gardenia': 'https://commons.wikimedia.org/wiki/Special:FilePath/Gardenia_jasminoides_flower_Argentina.jpg?width=1000',
    'Marigold': 'https://commons.wikimedia.org/wiki/Special:FilePath/Tagetes_erecta_chendumalli_chedi.jpg?width=1000',
    'Adenium (Desert Rose)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg?width=1000',
    'Canna Lily': 'https://commons.wikimedia.org/wiki/Special:FilePath/Canna_sp.jpg?width=1000',
    'Moss Rose (Portulaca)': 'https://commons.wikimedia.org/wiki/Special:FilePath/PortulacaGrandiflora.jpg?width=1000',
    'Bird of Paradise': 'https://commons.wikimedia.org/wiki/Special:FilePath/Ave-do-para%C3%ADso%2C_Strelitzia_reginae%2C_em_Bag%C3%A9%2C_Rio_Grande_do_Sul%2C_Brasil_-_55211233712.jpg?width=1000',
    'Cycas Palm (Sago Palm)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Cycas_inflorescence.jpg?width=1000',
    'Chrysanthemum': 'https://commons.wikimedia.org/wiki/Special:FilePath/Chrysanthemum.JPG?width=1000',
    'Petunia': 'https://commons.wikimedia.org/wiki/Special:FilePath/Pet%C3%BAnia_%28do_tupi_petyma%2C_%27tabaco%27%29.jpg?width=1000',
    'Sunflower': 'https://commons.wikimedia.org/wiki/Special:FilePath/Sunflower_sky_backdrop.jpg?width=1000',
    'Lavender': 'https://commons.wikimedia.org/wiki/Special:FilePath/Single_lavender_flower02.jpg?width=1000',
    'Hydrangea': 'https://commons.wikimedia.org/wiki/Special:FilePath/Hydrangea_arborescens_139866012.jpg?width=1000',
    'Peperomia': 'https://commons.wikimedia.org/wiki/Special:FilePath/Peperomia_obtusifolia_3-OB9.jpg?width=1000',
    'Dracaena Marginata': 'https://commons.wikimedia.org/wiki/Special:FilePath/Dracaena_reflexa.JPG?width=1000',
    'Dieffenbachia (Dumb Cane)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Dieffenbachia_oerstedii_kz2.jpg?width=1000',
    'Croton Petra': 'https://commons.wikimedia.org/wiki/Special:FilePath/Colpfl05.jpg?width=1000',
    'Schefflera (Umbrella Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Schefflera_arboricola%2C_vrugte%2C_a%2C_Pretoria.jpg?width=1000',
    'Ponytail Palm': 'https://commons.wikimedia.org/wiki/Special:FilePath/Beaucarnea_recurvata%2C_Ocampo%2C_Tamaulipas%2C_Mexico_1.jpg?width=1000',
    'String of Pearls': 'https://commons.wikimedia.org/wiki/Special:FilePath/Senecio_rowleyanus_leaves.jpg?width=1000',
    'Echeveria Succulent': 'https://commons.wikimedia.org/wiki/Special:FilePath/Echeveria_elegans_-_1.jpg?width=1000',
    'Haworthia Zebra Plant': 'https://commons.wikimedia.org/wiki/Special:FilePath/Winterbourne_-_Haworthia_attenuata_%286120983526%29.jpg?width=1000',
    'Kalanchoe': 'https://commons.wikimedia.org/wiki/Special:FilePath/Kalanchoe_blossfeldiana_3.jpg?width=1000',
    'Christmas Cactus': 'https://commons.wikimedia.org/wiki/Special:FilePath/Cactus_de_no%C3%ABl_rev.jpg?width=1000',
    'English Ivy': 'https://commons.wikimedia.org/wiki/Special:FilePath/Hedera_helix_Dover.jpg?width=1000',
    'Wandering Jew (Tradescantia)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Zebrina_pendula_20060521_2_closer.jpg?width=1000',
    'Coleus': 'https://commons.wikimedia.org/wiki/Special:FilePath/Plectranthus_scutellarioides_-_El_Yunque_nat_park_PR_IMG_2120.JPG?width=1000',
    'Begonia Rex': 'https://commons.wikimedia.org/wiki/Special:FilePath/Painted_Leaved_Begonia._Begonia_rex_Putz._Flore_des_serres_et_des_jardins_de_l%27Europe_v.12_%281857%29.jpg?width=1000',
    'Maranta (Prayer Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Maranta_leuconeura3.jpg?width=1000',
    'Alocasia (Elephant Ear)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Alocasia_macrorrhiza_-_Val_Rahmeh_-_DSC04449.JPG?width=1000',
    'Bamboo Palm': 'https://commons.wikimedia.org/wiki/Special:FilePath/Chamaedorea_seifrizii7.jpg?width=1000',
    'Kentia Palm': 'https://commons.wikimedia.org/wiki/Special:FilePath/Howea_forsteriana_Lord_Howe_Island.jpg?width=1000',
    'Norfolk Island Pine': 'https://commons.wikimedia.org/wiki/Special:FilePath/Norfolk-Island-Pines.jpg?width=1000',
    'Asparagus Fern': 'https://commons.wikimedia.org/wiki/Special:FilePath/Asparagus_setaceus_Leaves_2760px.jpg?width=1000',
    "Bird's Nest Fern": 'https://commons.wikimedia.org/wiki/Special:FilePath/Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg?width=1000',
    'Staghorn Fern': 'https://commons.wikimedia.org/wiki/Special:FilePath/Platycerium_bifurcatum.jpg?width=1000',
    'Air Plant (Tillandsia)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Tillandsia_fasciculata.jpg?width=1000',
    'Bromeliad': 'https://commons.wikimedia.org/wiki/Special:FilePath/Pineapple1.JPG?width=1000',
    'Orchid (Phalaenopsis)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg?width=1000',
    'Hoya (Wax Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg?width=1000',
    'Pilea (Chinese Money Plant)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Pilea_peperomioides_Chinese_money_plant.jpg?width=1000',
    'Oxalis (Purple Shamrock)': 'https://commons.wikimedia.org/wiki/Special:FilePath/Oxalis_triangularis6.jpg?width=1000',
    'Ficus Benjamina': 'https://commons.wikimedia.org/wiki/Special:FilePath/Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_%2824823189861%29.jpg?width=1000'
}
