"""Photographs for `seed_seeds`, written by `fetch_seed_photos`.

Keyed by the Wikipedia article the picture leads — the species itself,
so the catalogue shows the crop rather than a stock seed envelope.
Every URL was fetched and confirmed to answer with an image.
"""

PHOTOS: dict[str, str] = {
    'Alcea rosea': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Alcea_rosea_purple.jpg/1280px-Alcea_rosea_purple.jpg',
    'Alfalfa': 'https://commons.wikimedia.org/wiki/Special:FilePath/Sprouted_Alfalfa.jpg?width=1200',
    'Amaranthus tricolor': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/Amaranthus_tricolor_in_a_flower_bed_near_Notre-Dame_cathedral_in_Paris3.jpg/1280px-Amaranthus_tricolor_in_a_flower_bed_near_Notre-Dame_cathedral_in_Paris3.jpg',
    'Annona squamosa': 'https://upload.wikimedia.org/wikipedia/commons/4/42/Sugar_apple_on_tree.jpg',
    'Antirrhinum majus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Antirrhinum_majus_BCBG_%2802%29.jpg/1280px-Antirrhinum_majus_BCBG_%2802%29.jpg',
    'Basil': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/1280px-Ocimum_basilicum_8zz.jpg',
    'Beetroot': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Detroitdarkredbeets.png/1280px-Detroitdarkredbeets.png',
    'Bell pepper': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/1280px-Green-Yellow-Red-Pepper-2009.jpg',
    'Bok choy': 'https://upload.wikimedia.org/wikipedia/commons/9/99/Bok_Choy_%2849553125456%29.jpg',
    'Brassica juncea': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/Brassica_juncea_var._juncea.JPG/1280px-Brassica_juncea_var._juncea.JPG',
    'Broccoli': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/1280px-Broccoli_and_cross_section_edit.jpg',
    'Cabbage': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/1280px-Cabbage_and_cross_section_on_white.jpg',
    'Calabash': 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Courge_encore_verte.jpg',
    'Calendula officinalis': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Calendula_officinalis%2C_pot_marigold.JPG/1280px-Calendula_officinalis%2C_pot_marigold.JPG',
    'Callistephus chinensis': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Asterales_-_Callistephus_chinensis_-_20120823.jpg',
    'Carrot': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/1280px-Vegetable-Carrot-Bundle-wStalks.jpg',
    'Catharanthus roseus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Vinca_%28Catharanthus_roseus%29_cultivada_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55231652268.jpg/1280px-Vinca_%28Catharanthus_roseus%29_cultivada_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55231652268.jpg',
    'Cauliflower': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Chou-fleur_02.jpg/1280px-Chou-fleur_02.jpg',
    'Celery': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Celery_1.jpg/1280px-Celery_1.jpg',
    'Celosia argentea': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Celosia_argentea_flowering_q1.jpg/1280px-Celosia_argentea_flowering_q1.jpg',
    'Chard': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Chard_%28Beta_vulgaris_var_cicla%29.jpg/1280px-Chard_%28Beta_vulgaris_var_cicla%29.jpg',
    'Cherry tomato': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Tomates_cerises_Luc_Viatour.jpg/1280px-Tomates_cerises_Luc_Viatour.jpg',
    'Chia': 'https://commons.wikimedia.org/wiki/Special:FilePath/Salvia_hispanica_seeds.jpg?width=1200',
    'Chili pepper': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Madame_Jeanette_and_other_chillies.jpg/1280px-Madame_Jeanette_and_other_chillies.jpg',
    'Chives': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg/1280px-Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg',
    'Chrysanthemum': 'https://commons.wikimedia.org/wiki/Special:FilePath/Chrysanthemum_of_my_garden.jpg?width=1200',
    'Common sunflower': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/1280px-Sunflower_sky_backdrop.jpg',
    'Consolida ajacis': 'https://upload.wikimedia.org/wikipedia/commons/7/75/Consolida_ajacis_habito.jpg',
    'Coriander': 'https://commons.wikimedia.org/wiki/Special:FilePath/Coriandrum_sativum_4zz.jpg?width=1200',
    'Cosmos bipinnatus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Cosmos_bipinnatus_pink%2C_Burdwan%2C_West_Bengal%2C_India_10_01_2013.jpg/1280px-Cosmos_bipinnatus_pink%2C_Burdwan%2C_West_Bengal%2C_India_10_01_2013.jpg',
    'Cowpea': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Lobia.jpg',
    'Cucumber': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/1280px-ARS_cucumber.jpg',
    'Cumin': 'https://commons.wikimedia.org/wiki/Special:FilePath/Dried_cumin_seeds.jpg?width=1200',
    'Cymbopogon citratus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Gardenology.org-IMG_2892_rbgs11jan.jpg/1280px-Gardenology.org-IMG_2892_rbgs11jan.jpg',
    'Dahlia': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Dahlia_x_hybrida.jpg/1280px-Dahlia_x_hybrida.jpg',
    'Dianthus barbatus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Dianthus_barbatus_flowers_01.jpg/1280px-Dianthus_barbatus_flowers_01.jpg',
    'Dianthus caryophyllus': 'https://upload.wikimedia.org/wikipedia/commons/3/3b/W_carnation4051.jpg',
    'Dill': 'https://commons.wikimedia.org/wiki/Special:FilePath/Anethum_graveolens20090812_475.jpg?width=1200',
    'Eggplant': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG',
    'Fennel': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Foeniculum_July_2011-1a.jpg/1280px-Foeniculum_July_2011-1a.jpg',
    'Fenugreek': 'https://commons.wikimedia.org/wiki/Special:FilePath/Methi_leaves.jpg?width=1200',
    'Gaillardia pulchella': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Gaillardia_in_Aspen_%2891273%29.jpg/1280px-Gaillardia_in_Aspen_%2891273%29.jpg',
    'Gerbera jamesonii': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Gerbera_jamesonii_%28Asteraceae%29.jpg/1280px-Gerbera_jamesonii_%28Asteraceae%29.jpg',
    'Gomphrena globosa': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Gomphrena_globosa_All_Around_Purple_1zz.jpg/1280px-Gomphrena_globosa_All_Around_Purple_1zz.jpg',
    'Green bean': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Heaps_of_beans.jpg/1280px-Heaps_of_beans.jpg',
    'Guar': 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Cluster_bean-guar-Cyamopsis_psoralioides-Cyamopsis_tetragonolobus-TAMIL_NADU73.jpg',
    'Guava': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Guava_pink_fruit.jpg/1280px-Guava_pink_fruit.jpg',
    'Gypsophila elegans': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Gypsophila_elegans.jpg/1280px-Gypsophila_elegans.jpg',
    'Iberis umbellata': 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Brassicaceae_-_Iberis_umbellata.JPG',
    'Impatiens balsamina': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Impatiens_balsamina_28_08_2009.JPG/1280px-Impatiens_balsamina_28_08_2009.JPG',
    'Ipomoea purpurea': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Ipomoea_purpurea%2C_2021-08-31%2C_Beechview%2C_05.jpg/1280px-Ipomoea_purpurea%2C_2021-08-31%2C_Beechview%2C_05.jpg',
    'Kale': 'https://upload.wikimedia.org/wikipedia/commons/2/20/Boerenkool.jpg',
    'Kohlrabi': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Brassica_oleracea_var._gongylodes_%28kohlrabi%29.jpg/1280px-Brassica_oleracea_var._gongylodes_%28kohlrabi%29.jpg',
    'Lathyrus odoratus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Sweet_Pea-7.jpg/1280px-Sweet_Pea-7.jpg',
    'Leek': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Leek_on_white_background_-_0947.jpg/1280px-Leek_on_white_background_-_0947.jpg',
    'Lemon': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/P1030323.JPG',
    'Lettuce': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Iceberg_lettuce_in_SB.jpg/1280px-Iceberg_lettuce_in_SB.jpg',
    'Luffa': 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Luffa_aegyptica.jpg',
    'Luffa acutangula': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Luffa_acutangula_Chinese_okra.jpg/1280px-Luffa_acutangula_Chinese_okra.jpg',
    'Lupinus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Lupinus_polyphyllus_526960203.jpg/1280px-Lupinus_polyphyllus_526960203.jpg',
    'Mentha': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Mentha_spicata-IMG_6186.jpg/1280px-Mentha_spicata-IMG_6186.jpg',
    'Mirabilis jalapa': 'https://upload.wikimedia.org/wikipedia/commons/6/63/Gul-Abas-4-O%27clock_plant.JPG',
    'Momordica charantia': 'https://commons.wikimedia.org/wiki/Special:FilePath/Momordica_charantia_22052014.jpg?width=1200',
    'Moringa oleifera': 'https://upload.wikimedia.org/wikipedia/commons/2/2e/DrumstickFlower.jpg',
    'Muskmelon': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Canteloupe_and_cross_section.jpg/1280px-Canteloupe_and_cross_section.jpg',
    'Ocimum tenuiflorum': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Tulsi_or_Tulasi_Holy_basil.jpg/1280px-Tulsi_or_Tulasi_Holy_basil.jpg',
    'Okra': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Hong_Kong_Okra_Aug_25_2012.JPG/1280px-Hong_Kong_Okra_Aug_25_2012.JPG',
    'Onion': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/1280px-Mixed_onions.jpg',
    'Oregano': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Origanum_vulgare_-_harilik_pune.jpg/1280px-Origanum_vulgare_-_harilik_pune.jpg',
    'Pansy': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/PansyScan_%28cropped%29.jpg/1280px-PansyScan_%28cropped%29.jpg',
    'Papaver rhoeas': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Papaver_rhoeas_Lincolnshire_2026.jpg/1280px-Papaver_rhoeas_Lincolnshire_2026.jpg',
    'Papaya': 'https://commons.wikimedia.org/wiki/Special:FilePath/Carica_papaya_14_7_2012.jpg?width=1200',
    'Parsley': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Petroselinum.jpg/1280px-Petroselinum.jpg',
    'Passiflora edulis': 'https://commons.wikimedia.org/wiki/Special:FilePath/Passionfruit_and_cross_section.jpg?width=1200',
    'Pea': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Peas_in_pods_-_Studio.jpg/1280px-Peas_in_pods_-_Studio.jpg',
    'Petunia': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Pet%C3%BAnia_%28do_tupi_petyma%2C_%27tabaco%27%29.jpg/1280px-Pet%C3%BAnia_%28do_tupi_petyma%2C_%27tabaco%27%29.jpg',
    'Phlox drummondii': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Phlox_drummondii-5.JPG/1280px-Phlox_drummondii-5.JPG',
    'Pitaya': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Pitaya_cross_section_ed2.jpg/1280px-Pitaya_cross_section_ed2.jpg',
    'Pomegranate': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/1280px-Pomegranate_Juice_%282019%29.jpg',
    'Portulaca grandiflora': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/PortulacaGrandiflora.jpg/1280px-PortulacaGrandiflora.jpg',
    'Praecitrullus fistulosus': 'https://upload.wikimedia.org/wikipedia/commons/8/80/Tinda.jpg',
    'Pumpkin': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/FrenchMarketPumpkinsB.jpg/1280px-FrenchMarketPumpkinsB.jpg',
    'Radish': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Radish_3371103037_4ab07db0bf_o.jpg/1280px-Radish_3371103037_4ab07db0bf_o.jpg',
    'Rosemary': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Rosemary_in_bloom.JPG/1280px-Rosemary_in_bloom.JPG',
    'Salvia officinalis': 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Salvia_officinalis0.jpg',
    'Salvia splendens': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Mudas_de_alegrias-de-jardim%2C_ou_s%C3%A1lvia_01.jpg/1280px-Mudas_de_alegrias-de-jardim%2C_ou_s%C3%A1lvia_01.jpg',
    'Scallion': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/CSA-Red-Spring-Onions.jpg/1280px-CSA-Red-Spring-Onions.jpg',
    'Spinach': 'https://upload.wikimedia.org/wikipedia/commons/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg',
    'Stevia rebaudiana': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Stevia_rebaudiana_flowers.jpg/1280px-Stevia_rebaudiana_flowers.jpg',
    'Strawberry': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/1280px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg',
    'Sweet corn': 'https://upload.wikimedia.org/wikipedia/commons/7/79/VegCorn.jpg',
    'Tagetes erecta': 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Tagetes_x_erecta1.jpg',
    'Tagetes patula': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/French_marigold_Tagetes_patula.jpg/1280px-French_marigold_Tagetes_patula.jpg',
    'Thyme': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Thyme-Bundle.jpg/1280px-Thyme-Bundle.jpg',
    'Tomato': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/1280px-Tomato_je.jpg',
    'Trachyspermum ammi': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Carom_Flowers.jpg/1280px-Carom_Flowers.jpg',
    'Trichosanthes cucumerina': 'https://commons.wikimedia.org/wiki/Special:FilePath/Trichosanthes_cucumerina_%28snake_gourd%29.jpg?width=1200',
    'Tropaeolum majus': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Tropaeolum_majus_2005_G1.jpg/1280px-Tropaeolum_majus_2005_G1.jpg',
    'Turnip': 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Turnip_2622027.jpg',
    'Verbena': 'https://commons.wikimedia.org/wiki/Special:FilePath/Verbena_rigida_flower.jpg?width=1200',
    'Watermelon': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg/1280px-Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg',
    'Wax gourd': 'https://commons.wikimedia.org/wiki/Special:FilePath/Benincasa_hispida-1-selvapuram-coimbatore-India.jpg?width=1200',
    'Wheatgrass': 'https://upload.wikimedia.org/wikipedia/commons/6/67/Wheatgrass.jpg',
    'Zinnia elegans': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Zinnienbl%C3%BCte_Zinnia_elegans_stack15_20190722-RM-7222254.jpg/1280px-Zinnienbl%C3%BCte_Zinnia_elegans_stack15_20190722-RM-7222254.jpg',
    'Zucchini': 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/1280px-CSA-Striped-Zucchini.jpg',
}
