"""The seed-packet range: what goes in the catalogue, and the article each
photograph comes from.

One row per packet:
  (name, wikipedia article, group, price ₹, germination days, days to harvest,
   sowing season, sunlight, the one line that is particular to this packet)

`wikipedia article` is the title whose lead photograph illustrates the packet —
the species itself, so the picture is the real crop and not a stock envelope.
`group` keys into the sub-categories built by `seed_seeds`.
"""

# fmt: off
SEEDS: list[tuple] = [
    # ── Vegetable ────────────────────────────────────────────────────────────
    ("Tomato Seeds (Hybrid)", "Tomato", "vegetable", 69, "6-10", "70-80", "Jun-Jul, Oct-Nov", "Full Sun", "Heavy-bearing determinate vine for pots and beds alike"),
    ("Cherry Tomato Seeds", "Cherry tomato", "vegetable", 79, "6-10", "65-75", "Jun-Jul, Oct-Nov", "Full Sun", "Sweet bite-sized trusses that keep coming all season"),
    ("Brinjal Seeds (Long Purple)", "Eggplant", "vegetable", 59, "8-12", "80-90", "Jun-Jul, Nov-Dec", "Full Sun", "Glossy long fruit, the dependable Indian kitchen brinjal"),
    ("Green Chilli Seeds", "Chili pepper", "vegetable", 49, "8-14", "70-80", "Feb-Mar, Jun-Jul", "Full Sun", "Sharp, thin-skinned chillies that fruit for months"),
    ("Capsicum Seeds (Bell Pepper)", "Bell pepper", "vegetable", 89, "10-15", "80-90", "Jun-Jul, Nov-Dec", "Full Sun", "Thick-walled blocky fruit in green, red and yellow"),
    ("Okra Seeds (Lady Finger)", "Okra", "vegetable", 45, "5-8", "45-55", "Feb-Mar, Jun-Jul", "Full Sun", "Tender five-ridged pods picked young every other day"),
    ("Cucumber Seeds", "Cucumber", "vegetable", 49, "5-8", "45-55", "Feb-Mar, Jun-Jul", "Full Sun", "Crisp salad cucumbers off a trellis in under two months"),
    ("Bottle Gourd Seeds (Lauki)", "Calabash", "vegetable", 55, "7-10", "60-70", "Feb-Mar, Jun-Jul", "Full Sun", "Vigorous climber carrying long pale-green gourds"),
    ("Bitter Gourd Seeds (Karela)", "Momordica charantia", "vegetable", 59, "8-12", "55-65", "Feb-Mar, Jun-Jul", "Full Sun", "Ridged dark-green fruit on a fast-covering vine"),
    ("Ridge Gourd Seeds (Turai)", "Luffa acutangula", "vegetable", 49, "7-10", "55-65", "Feb-Mar, Jun-Jul", "Full Sun", "Tender ribbed gourds borne in flushes through the rains"),
    ("Sponge Gourd Seeds (Nenua)", "Luffa", "vegetable", 49, "7-10", "60-70", "Feb-Mar, Jun-Jul", "Full Sun", "Smooth gourds for the pan young, for scrubbers when dried"),
    ("Pumpkin Seeds (Kaddu)", "Pumpkin", "vegetable", 55, "6-10", "90-110", "Feb-Mar, Jun-Jul", "Full Sun", "Sprawling vine with keeping-quality orange fruit"),
    ("Ash Gourd Seeds (Petha)", "Wax gourd", "vegetable", 55, "7-12", "90-110", "Jan-Feb, Jun-Jul", "Full Sun", "Waxy white gourds that store for months after harvest"),
    ("Snake Gourd Seeds (Chichinda)", "Trichosanthes cucumerina", "vegetable", 59, "8-12", "70-80", "Feb-Mar, Jun-Jul", "Full Sun", "Long coiling fruit best grown over an overhead frame"),
    ("Tinda Seeds (Apple Gourd)", "Praecitrullus fistulosus", "vegetable", 59, "7-12", "60-70", "Feb-Mar, Jun-Jul", "Full Sun", "Round tender gourds picked at a golf-ball size"),
    ("Zucchini Seeds", "Zucchini", "vegetable", 89, "5-8", "45-55", "Feb-Mar, Oct-Nov", "Full Sun", "Bush courgette that crops heavily in a single square metre"),
    ("Carrot Seeds (Nantes)", "Carrot", "vegetable", 59, "10-18", "75-90", "Aug-Nov", "Full Sun", "Sweet blunt-tipped roots for deep pots and loose beds"),
    ("Radish Seeds (White Long)", "Radish", "vegetable", 39, "4-7", "35-45", "Aug-Jan", "Full Sun", "Crisp mild roots ready inside six weeks of sowing"),
    ("Beetroot Seeds", "Beetroot", "vegetable", 55, "8-14", "60-75", "Sep-Nov", "Full Sun", "Deep-red globes with leaves good enough to cook"),
    ("Turnip Seeds (Shalgam)", "Turnip", "vegetable", 45, "5-10", "50-60", "Sep-Nov", "Full Sun", "Quick purple-shouldered roots for cool-weather beds"),
    ("Onion Seeds (Red)", "Onion", "vegetable", 69, "8-14", "120-150", "Oct-Dec", "Full Sun", "Pungent red storage bulbs raised from a nursery bed"),
    ("Spinach Seeds (Palak)", "Spinach", "vegetable", 39, "6-10", "35-45", "Sep-Feb", "Partial Shade", "Thick tender leaves that regrow after every cutting"),
    ("Amaranth Seeds (Lal Saag)", "Amaranthus tricolor", "vegetable", 39, "4-7", "25-35", "Mar-Aug", "Full Sun", "Crimson-leaved saag cut repeatedly from one sowing"),
    ("Fenugreek Seeds (Methi)", "Fenugreek", "vegetable", 35, "3-6", "25-30", "Sep-Feb", "Full Sun", "Aromatic methi leaves off a windowsill tray in a month"),
    ("Cabbage Seeds", "Cabbage", "vegetable", 69, "7-12", "80-100", "Sep-Nov", "Full Sun", "Tight round heads that hold well in the winter garden"),
    ("Cauliflower Seeds", "Cauliflower", "vegetable", 79, "7-12", "90-110", "Jun-Oct", "Full Sun", "Snow-white self-blanching curds for the cool months"),
    ("Broccoli Seeds", "Broccoli", "vegetable", 99, "7-12", "80-95", "Sep-Nov", "Full Sun", "A central crown first, then side shoots for weeks"),
    ("Lettuce Seeds (Butterhead)", "Lettuce", "vegetable", 69, "4-8", "45-60", "Sep-Feb", "Partial Shade", "Soft loose heads for salad, happy in a shallow trough"),
    ("Kale Seeds (Curly)", "Kale", "vegetable", 89, "5-10", "55-70", "Sep-Nov", "Full Sun", "Frilled leaves that sweeten once the nights turn cold"),
    ("Swiss Chard Seeds", "Chard", "vegetable", 79, "7-14", "50-60", "Sep-Dec", "Partial Shade", "Rainbow stems, cut-and-come-again through the winter"),
    ("Bok Choy Seeds", "Bok choy", "vegetable", 79, "4-8", "40-50", "Sep-Jan", "Partial Shade", "Crunch-stemmed Asian green ready for the wok in six weeks"),
    ("Kohlrabi Seeds (Knol Khol)", "Kohlrabi", "vegetable", 69, "5-10", "55-70", "Sep-Nov", "Full Sun", "Swollen stems eaten raw like a sweeter turnip"),
    ("Pea Seeds (Garden Peas)", "Pea", "vegetable", 59, "7-12", "60-70", "Oct-Dec", "Full Sun", "Sweet shelling peas on a short self-supporting vine"),
    ("French Bean Seeds", "Green bean", "vegetable", 55, "6-10", "45-55", "Feb-Mar, Sep-Oct", "Full Sun", "Stringless bush beans that need no staking at all"),
    ("Cowpea Seeds (Lobia)", "Cowpea", "vegetable", 45, "4-8", "45-55", "Mar-Jul", "Full Sun", "Heat-proof pods that crop when little else will"),
    ("Cluster Bean Seeds (Guar)", "Guar", "vegetable", 45, "5-10", "50-60", "Mar-Jul", "Full Sun", "Drought-hardy clusters, a dependable summer vegetable"),
    ("Sweet Corn Seeds", "Sweet corn", "vegetable", 89, "6-10", "75-90", "Feb-Mar, Jun-Jul", "Full Sun", "Sugary cobs — sow in a block so they pollinate properly"),
    ("Drumstick Seeds (Moringa)", "Moringa oleifera", "vegetable", 69, "10-14", "180-240", "Mar-Aug", "Full Sun", "A fast tree giving pods and the most nutritious of leaves"),
    ("Celery Seeds", "Celery", "vegetable", 79, "14-21", "100-120", "Sep-Nov", "Partial Shade", "Crisp aromatic stalks for salads and stock pots"),
    ("Leek Seeds", "Leek", "vegetable", 79, "10-14", "100-120", "Sep-Nov", "Full Sun", "Mild winter alliums blanched by earthing up the stems"),
    ("Mustard Greens Seeds (Sarson)", "Brassica juncea", "vegetable", 35, "4-7", "30-40", "Sep-Dec", "Full Sun", "Peppery saag leaves, the fastest green of the winter"),
    ("Spring Onion Seeds", "Scallion", "vegetable", 45, "7-12", "50-60", "Sep-Jan", "Full Sun", "Slim stalks you can cut and let regrow from the base"),

    # ── Flower ───────────────────────────────────────────────────────────────
    ("Marigold Seeds (African)", "Tagetes erecta", "flower", 49, "5-8", "45-55", "Jun-Jul, Sep-Oct", "Full Sun", "Dense orange pompoms, and a guard against soil pests"),
    ("French Marigold Seeds", "Tagetes patula", "flower", 45, "5-8", "45-55", "Jun-Jul, Sep-Oct", "Full Sun", "Compact bicolour heads for edging and balcony boxes"),
    ("Sunflower Seeds (Dwarf)", "Common sunflower", "flower", 55, "5-10", "60-70", "Feb-Mar, Jun-Jul", "Full Sun", "Knee-high sunflowers that hold up in a windy balcony"),
    ("Zinnia Seeds (Mixed)", "Zinnia elegans", "flower", 45, "5-8", "50-60", "Feb-Jul", "Full Sun", "Jewel-bright daisies that flower on through the heat"),
    ("Cosmos Seeds", "Cosmos bipinnatus", "flower", 45, "5-10", "60-75", "Jun-Aug", "Full Sun", "Airy stems above ferny foliage — a butterfly magnet"),
    ("Petunia Seeds (Grandiflora)", "Petunia", "flower", 69, "7-14", "70-85", "Sep-Nov", "Full Sun", "Trumpet blooms that spill over the rim of a hanging pot"),
    ("Pansy Seeds", "Pansy", "flower", 79, "10-14", "80-95", "Sep-Oct", "Partial Shade", "Velvet-faced winter flowers in deep inky colours"),
    ("Dahlia Seeds", "Dahlia", "flower", 89, "7-14", "90-110", "Oct-Nov", "Full Sun", "Full double heads raised from seed in a single season"),
    ("Balsam Seeds (Gul Mehendi)", "Impatiens balsamina", "flower", 39, "7-12", "60-70", "Jun-Jul", "Partial Shade", "The old monsoon favourite, flowering along every stem"),
    ("Nasturtium Seeds", "Tropaeolum majus", "flower", 59, "7-12", "55-65", "Sep-Nov", "Full Sun", "Round leaves and peppery edible flowers for salads"),
    ("Calendula Seeds", "Calendula officinalis", "flower", 49, "6-10", "60-70", "Sep-Nov", "Full Sun", "Pot marigold — golden petals, and a herb in its own right"),
    ("China Aster Seeds", "Callistephus chinensis", "flower", 49, "7-12", "80-90", "Sep-Nov", "Full Sun", "Quilled heads that last a fortnight in the vase"),
    ("Phlox Seeds", "Phlox drummondii", "flower", 49, "7-12", "70-80", "Sep-Nov", "Full Sun", "Low cushions smothered in flower through a cool spring"),
    ("Salvia Seeds (Scarlet)", "Salvia splendens", "flower", 59, "10-15", "80-90", "Sep-Nov", "Full Sun", "Upright scarlet spikes that read from across a garden"),
    ("Verbena Seeds", "Verbena", "flower", 59, "10-20", "75-90", "Sep-Nov", "Full Sun", "Flat clusters in rose and violet, loved by butterflies"),
    ("Snapdragon Seeds (Antirrhinum)", "Antirrhinum majus", "flower", 69, "7-14", "90-100", "Sep-Oct", "Full Sun", "Hinged dragon-mouth florets up a tall cutting stem"),
    ("Sweet Pea Seeds", "Lathyrus odoratus", "flower", 69, "10-15", "90-110", "Oct-Nov", "Full Sun", "A climber worth growing for the scent alone"),
    ("Morning Glory Seeds", "Ipomoea purpurea", "flower", 45, "5-10", "60-70", "Feb-Jul", "Full Sun", "Fast screen of blue trumpets open by first light"),
    ("Four O'Clock Seeds (Gul Abbas)", "Mirabilis jalapa", "flower", 39, "7-12", "60-70", "Feb-Jul", "Full Sun", "Scented flowers that open as the afternoon cools"),
    ("Gaillardia Seeds (Blanket Flower)", "Gaillardia pulchella", "flower", 45, "7-14", "70-80", "Feb-Jul", "Full Sun", "Red-and-gold wheels on a plant that shrugs off drought"),
    ("Celosia Seeds (Cockscomb)", "Celosia argentea", "flower", 45, "7-12", "65-75", "Jun-Aug", "Full Sun", "Plush crested heads that dry without losing colour"),
    ("Portulaca Seeds (Moss Rose)", "Portulaca grandiflora", "flower", 39, "7-12", "50-60", "Feb-Jun", "Full Sun", "Succulent mat that flowers hardest on the hottest wall"),
    ("Vinca Seeds (Sadabahar)", "Catharanthus roseus", "flower", 45, "10-15", "70-80", "Feb-Jul", "Full Sun", "In flower nearly every week of the year, as the name says"),
    ("Hollyhock Seeds", "Alcea rosea", "flower", 59, "10-14", "100-120", "Sep-Oct", "Full Sun", "Tall spires for the back of a bed, up to two metres"),
    ("Larkspur Seeds", "Consolida ajacis", "flower", 55, "14-21", "90-110", "Oct-Nov", "Full Sun", "Spires of blue and white that dry beautifully"),
    ("Carnation Seeds", "Dianthus caryophyllus", "flower", 79, "10-15", "100-120", "Sep-Nov", "Full Sun", "Clove-scented frilled blooms on wiry grey stems"),
    ("Dianthus Seeds (Sweet William)", "Dianthus barbatus", "flower", 59, "7-14", "80-95", "Sep-Nov", "Full Sun", "Fringed clusters in every shade from white to near-black"),
    ("Chrysanthemum Seeds", "Chrysanthemum", "flower", 69, "10-15", "100-120", "Jun-Aug", "Full Sun", "The festival flower, in bloom through the short days"),
    ("Gomphrena Seeds (Globe Amaranth)", "Gomphrena globosa", "flower", 45, "7-14", "70-80", "Feb-Jul", "Full Sun", "Papery clover-like heads that hold colour when dried"),
    ("Candytuft Seeds", "Iberis umbellata", "flower", 45, "7-14", "60-75", "Sep-Nov", "Full Sun", "Flat white and pink heads along a tidy low edge"),
    ("Lupin Seeds", "Lupinus", "flower", 79, "14-21", "100-120", "Sep-Nov", "Full Sun", "Dense colour spikes, and roots that feed the soil"),
    ("Poppy Seeds (Corn Poppy)", "Papaver rhoeas", "flower", 55, "10-15", "70-85", "Oct-Nov", "Full Sun", "Tissue-paper scarlet flowers over blue-green leaves"),
    ("Gypsophila Seeds (Baby's Breath)", "Gypsophila elegans", "flower", 59, "7-14", "60-75", "Sep-Nov", "Full Sun", "A cloud of tiny white stars — the florist's filler"),
    ("Gerbera Seeds", "Gerbera jamesonii", "flower", 99, "14-21", "120-150", "Sep-Nov", "Bright Indirect", "Big single daisies on long clean cutting stems"),

    # ── Herb ─────────────────────────────────────────────────────────────────
    ("Tulsi Seeds (Holy Basil)", "Ocimum tenuiflorum", "herb", 45, "7-14", "50-60", "Feb-Jul", "Full Sun", "The household tulsi, for the courtyard and for kadha"),
    ("Sweet Basil Seeds", "Basil", "herb", 55, "5-10", "45-55", "Feb-Aug", "Full Sun", "Broad Genovese leaves — pesto from a single windowbox"),
    ("Coriander Seeds (Dhania)", "Coriander", "herb", 35, "7-14", "35-45", "Sep-Feb", "Partial Shade", "Split the seed before sowing and cut leaves for weeks"),
    ("Mint Seeds (Pudina)", "Mentha", "herb", 49, "10-15", "60-70", "Feb-Aug", "Partial Shade", "Keep it in its own pot — it will take a bed otherwise"),
    ("Parsley Seeds", "Parsley", "herb", 59, "14-28", "70-90", "Sep-Nov", "Partial Shade", "Flat-leaf parsley, slow to start and then endless"),
    ("Oregano Seeds", "Oregano", "herb", 69, "7-14", "80-90", "Feb-Mar, Sep-Oct", "Full Sun", "Pizza herb that gets stronger in flavour as it dries"),
    ("Thyme Seeds", "Thyme", "herb", 69, "14-21", "90-100", "Feb-Mar, Sep-Oct", "Full Sun", "Tiny grey-green leaves on a woody, drought-proof mat"),
    ("Rosemary Seeds", "Rosemary", "herb", 89, "15-25", "120-150", "Sep-Nov", "Full Sun", "Resinous needles for the roasting tray, slow from seed"),
    ("Dill Seeds (Sowa)", "Dill", "herb", 45, "7-14", "45-60", "Sep-Dec", "Full Sun", "Feathery fronds for fish, pickles and winter saag"),
    ("Sage Seeds", "Salvia officinalis", "herb", 79, "14-21", "90-110", "Sep-Nov", "Full Sun", "Soft grey leaves, as useful in a border as in butter"),
    ("Chives Seeds", "Chives", "herb", 69, "10-20", "70-85", "Sep-Nov", "Partial Shade", "Fine onion tips to snip over anything, all year"),
    ("Lemongrass Seeds", "Cymbopogon citratus", "herb", 59, "10-20", "90-120", "Mar-Jul", "Full Sun", "Citrus stems for chai and curry, from a clump that spreads"),
    ("Ajwain Seeds (Carom)", "Trachyspermum ammi", "herb", 45, "7-14", "90-110", "Oct-Dec", "Full Sun", "Thymol-scented seed for parathas and for the stomach"),
    ("Fennel Seeds (Saunf)", "Fennel", "herb", 45, "7-14", "90-110", "Sep-Nov", "Full Sun", "Aniseed fronds first, then the seed heads to dry"),
    ("Cumin Seeds (Jeera)", "Cumin", "herb", 55, "7-14", "100-120", "Oct-Nov", "Full Sun", "A cool-season crop that needs dry weather to ripen"),
    ("Stevia Seeds", "Stevia rebaudiana", "herb", 99, "14-21", "90-110", "Feb-Apr", "Full Sun", "Leaves many times sweeter than sugar, with no calories"),

    # ── Fruit ────────────────────────────────────────────────────────────────
    ("Watermelon Seeds", "Watermelon", "fruit", 69, "5-10", "80-100", "Jan-Mar", "Full Sun", "Dark-skinned melons with crisp red flesh for high summer"),
    ("Muskmelon Seeds (Kharbooja)", "Muskmelon", "fruit", 69, "5-10", "75-90", "Jan-Mar", "Full Sun", "Netted sweet melons that scent the garden as they ripen"),
    ("Papaya Seeds (Red Lady)", "Papaya", "fruit", 89, "14-21", "240-300", "Feb-Mar, Jun-Jul", "Full Sun", "Dwarf, fast-fruiting papaya you can pick standing up"),
    ("Strawberry Seeds", "Strawberry", "fruit", 129, "14-28", "150-180", "Sep-Nov", "Bright Indirect", "Everbearing runners for a cool balcony and a hanging pot"),
    ("Guava Seeds", "Guava", "fruit", 79, "15-30", "730-900", "Feb-Mar, Jun-Jul", "Full Sun", "A hardy tree from seed, and a pot-grown bonsai subject"),
    ("Custard Apple Seeds (Sitaphal)", "Annona squamosa", "fruit", 79, "20-30", "900-1100", "Jun-Jul", "Full Sun", "Scaly green fruit with cream-sweet pulp, tough once grown"),
    ("Pomegranate Seeds (Anar)", "Pomegranate", "fruit", 89, "20-40", "730-900", "Feb-Mar, Jun-Jul", "Full Sun", "Drought-hardy, and handsome in flower long before fruit"),
    ("Dragon Fruit Seeds", "Pitaya", "fruit", 149, "15-30", "540-730", "Mar-Jul", "Full Sun", "Night-flowering cactus carrying magenta-skinned fruit"),
    ("Passion Fruit Seeds", "Passiflora edulis", "fruit", 119, "15-30", "365-540", "Feb-Mar, Jun-Jul", "Full Sun", "A vigorous vine, as much for the flower as the fruit"),
    ("Lemon Seeds", "Lemon", "fruit", 69, "14-28", "900-1200", "Feb-Mar, Jun-Jul", "Full Sun", "Thorny evergreen for a big pot — fragrant in flower"),

    # ── Microgreens ──────────────────────────────────────────────────────────
    ("Wheatgrass Seeds (Microgreens)", "Wheatgrass", "microgreen", 99, "2-3", "8-10", "All Season", "Bright Indirect", "A tray of juicing grass on the kitchen counter in a week"),
    ("Alfalfa Sprouting Seeds", "Alfalfa", "microgreen", 89, "2-3", "5-7", "All Season", "Bright Indirect", "Fine crisp sprouts for sandwiches, grown in a jar"),
    ("Mustard Microgreens Seeds", "Brassica juncea", "microgreen", 79, "2-4", "8-12", "All Season", "Bright Indirect", "A hot mustard bite in a shoot a few centimetres tall"),
    ("Radish Microgreens Seeds", "Radish", "microgreen", 79, "2-4", "7-10", "All Season", "Bright Indirect", "Pink-stemmed shoots with the full sharpness of the root"),
    ("Sunflower Microgreens Seeds", "Common sunflower", "microgreen", 89, "2-4", "8-12", "All Season", "Bright Indirect", "Thick nutty shoots — the most filling of the microgreens"),
    ("Broccoli Microgreens Seeds", "Broccoli", "microgreen", 99, "2-4", "8-12", "All Season", "Bright Indirect", "Mild shoots carrying far more sulforaphane than the head"),
    ("Pea Shoots Seeds", "Pea", "microgreen", 79, "3-5", "10-14", "All Season", "Bright Indirect", "Sweet tendrils that regrow once after the first cut"),
    ("Fenugreek Microgreens Seeds", "Fenugreek", "microgreen", 69, "2-4", "7-10", "All Season", "Bright Indirect", "Methi shoots, bitter-fresh and ready inside a week"),
    ("Chia Sprouting Seeds", "Chia", "microgreen", 99, "2-4", "7-10", "All Season", "Bright Indirect", "Gel-coated seed that sprouts on a damp terracotta tray"),
    ("Beetroot Microgreens Seeds", "Beetroot", "microgreen", 89, "3-6", "10-14", "All Season", "Bright Indirect", "Magenta stems that colour a plate as much as flavour it"),
]
# fmt: on

GROUPS = {
    "vegetable": ("Vegetable Seeds", "vegetable-seeds"),
    "flower": ("Flower Seeds", "flower-seeds"),
    "herb": ("Herb Seeds", "herb-seeds"),
    "fruit": ("Fruit Seeds", "fruit-seeds"),
    "microgreen": ("Microgreen Seeds", "microgreen-seeds"),
}
