"""Everything the nursery sells that is not a plant or a packet of seed.

One row per product:
  (name, price ₹, photo search term, words the filename must carry, blurb)

The search term and its must-words are what `_commons.gallery` uses to find
three photographs of the item; the must-words keep a search for "watering can"
from returning a painting of a girl holding one.
"""

# fmt: off
SUPPLIES: dict[str, list[tuple]] = {
"pots": [
    ("Terracotta Pot — 6 inch", 149, "terracotta flower pot", ["terracotta"], "Unglazed clay that breathes, so roots never sit wet."),
    ("Terracotta Pot Set of 3", 399, "terracotta pots stacked", ["terracotta"], "Three graduated sizes for a shelf, a sill and a corner."),
    ("Glazed Ceramic Planter — 8 inch", 549, "glazed ceramic flower pot", ["ceramic"], "A fired glaze finish that holds colour for years indoors."),
    ("White Ceramic Pot with Saucer", 449, "white ceramic plant pot", ["ceramic"], "The clean white cylinder that suits any leaf shape."),
    ("Hanging Basket with Chain", 349, "hanging flower basket", ["hanging", "basket"], "Steel chain and drip tray for trailing pothos and ferns."),
    ("Railing Planter — Balcony", 499, "window box planter railing", ["planter"], "Clamps to a balcony rail so the floor stays clear."),
    ("Self-Watering Pot — 7 inch", 599, "self watering planter", ["watering"], "A reservoir below the soil that carries a week on its own."),
    ("HDPE Grow Bag — Pack of 5", 299, "grow bag plants", ["bag"], "UV-treated fabric bags that fold flat between seasons."),
    ("Nursery Plastic Pot — Pack of 10", 199, "plastic nursery plant pot", ["pot"], "Light propagation pots with drainage already punched."),
    ("Woven Basket Planter", 649, "wicker basket planter", ["basket"], "A natural fibre sleeve to hide a plain nursery pot."),
],
"soil": [
    ("All-Purpose Potting Mix — 5 kg", 299, "potting soil mix", ["potting"], "Cocopeat, compost and perlite, pre-mixed and ready to fill."),
    ("Cocopeat Block — 5 kg Expandable", 249, "coco peat coconut coir", ["coir"], "Expands to 75 litres of airy, pH-balanced growing medium."),
    ("Vermicompost — 5 kg", 279, "vermicompost", ["vermicompost"], "Earthworm castings — the gentlest feed a seedling can get."),
    ("Red Soil — 5 kg", 149, "red soil laterite", ["soil"], "The iron-rich base Indian gardens have always been built on."),
    ("River Sand — 5 kg", 129, "river sand", ["sand"], "Coarse washed sand to open up a mix that holds too much water."),
    ("Perlite — 1 kg", 349, "perlite", ["perlite"], "Volcanic glass beads that keep the root zone breathing."),
    ("Vermiculite — 1 kg", 379, "vermiculite", ["vermiculite"], "Holds water and nutrients, then lets them go slowly."),
    ("Leaf Compost — 5 kg", 229, "leaf compost humus", ["compost"], "Crumbly, fully rotted leaf mould for topping up a tired pot."),
],
"fertilisers": [
    ("Bone Meal — 1 kg", 249, "bone meal fertilizer", ["bone"], "Slow-release phosphorus for roots, bulbs and heavy flowering."),
    ("Neem Cake — 1 kg", 229, "neem cake fertilizer", ["neem"], "Feeds the soil and keeps grubs off the roots at the same time."),
    ("Mustard Cake Powder — 1 kg", 219, "mustard oil cake", ["mustard"], "The old nitrogen feed — soak overnight and water it in."),
    ("NPK 19:19:19 — 900 g", 299, "npk fertilizer granules", ["fertilizer"], "A balanced water-soluble feed for the whole growing season."),
    ("Seaweed Extract — 500 ml", 399, "seaweed fertilizer kelp", ["seaweed"], "Growth hormones and trace elements from cold-water kelp."),
    ("Epsom Salt — 900 g", 179, "epsom salt magnesium sulfate", ["epsom"], "Magnesium for leaves that have gone pale between the veins."),
    ("Organic Liquid Fertiliser — 500 ml", 329, "liquid fertilizer bottle", ["fertilizer"], "A fortnightly drink that will not burn a tender root."),
    ("Rose & Flower Mix — 1 kg", 269, "rose fertilizer", ["fertilizer"], "Potash-heavy blend for bigger blooms and stronger stems."),
    ("Humic Acid Granules — 500 g", 299, "humic acid soil", ["humic"], "Unlocks the nutrients a tired potting mix is already holding."),
],
"garden-tools": [
    ("Hand Trowel — Stainless Steel", 249, "garden trowel", ["trowel"], "A forged blade that will not bend in compacted soil."),
    ("Hand Fork", 229, "garden hand fork tool", ["fork"], "Three tines for loosening the crust and lifting weeds."),
    ("Khurpi — Indian Weeding Hoe", 199, "khurpi hand hoe", ["hoe"], "The short-handled blade every Indian gardener learns on."),
    ("Pruning Secateurs", 449, "secateurs pruning", ["secateur"], "Bypass blades that cut cleanly instead of crushing a stem."),
    ("Garden Scissors", 249, "garden scissors pruning shears", ["scissors"], "Fine tips for deadheading and harvesting herbs."),
    ("Hand Weeder", 199, "hand weeder tool", ["weeder"], "A forked tip that takes the tap root out with the weed."),
    ("Gardening Gloves", 249, "gardening gloves", ["glove"], "Coated palms for thorns, grit and wet potting mix."),
    ("Garden Rake — Hand Size", 229, "hand rake garden tool", ["rake"], "Levels a seed bed and clears leaf litter off a pot."),
    ("5-Piece Garden Tool Set", 899, "garden tools set", ["tool"], "Trowel, fork, weeder, rake and pruner in one roll."),
],
"watering-solutions": [
    ("Watering Can — 5 Litre", 499, "watering can", ["watering", "can"], "A long rose that soaks a bed without washing out seed."),
    ("Hand Mist Sprayer — 500 ml", 199, "spray bottle mist", ["spray"], "Fine mist for ferns, calatheas and anything that wants humidity."),
    ("Pressure Sprayer — 2 Litre", 649, "garden pressure sprayer", ["sprayer"], "Pump-primed, for neem oil over a whole balcony in one go."),
    ("Garden Hose — 15 m", 999, "garden hose", ["hose"], "Kink-resistant braid with brass fittings at both ends."),
    ("Hose Spray Nozzle", 349, "garden hose nozzle", ["nozzle"], "Seven patterns from a jet to a mist, on one dial."),
    ("Drip Irrigation Kit — 20 Plants", 1299, "drip irrigation", ["drip"], "Everything a balcony needs to water itself while you travel."),
    ("Rotating Sprinkler", 549, "garden sprinkler", ["sprinkler"], "Covers a small lawn from a single standing point."),
    ("Self-Watering Spikes — Pack of 4", 249, "plant watering spike", ["water"], "Screws onto a bottle and keeps a pot going for a fortnight."),
],
"pest-control": [
    ("Neem Oil — 250 ml", 299, "neem oil", ["neem"], "Cold-pressed, for aphids, mealybugs and the mite you missed."),
    ("Yellow Sticky Traps — Pack of 10", 199, "yellow sticky trap insects", ["trap"], "Catches whitefly and fungus gnats before they breed."),
    ("Insecticidal Soap — 500 ml", 279, "insecticidal soap spray", ["soap"], "Potassium soap that clears soft-bodied pests and rinses off."),
    ("Sulphur Powder — 500 g", 199, "sulfur powder", ["sulfur"], "The old answer to powdery mildew on roses and cucurbits."),
    ("Copper Fungicide — 250 g", 329, "copper fungicide bordeaux", ["copper"], "For leaf spot and blight through a long wet monsoon."),
    ("Trichoderma Viride — 500 g", 349, "trichoderma fungus", ["trichoderma"], "A friendly fungus that crowds out root rot in the soil."),
    ("Diatomaceous Earth — 500 g", 399, "diatomaceous earth", ["diatomaceous"], "Ground fossil silica — mechanical, not chemical, pest control."),
    ("Pheromone Fruit Fly Trap", 299, "pheromone insect trap", ["trap"], "Lures the male fly away before the fruit is ever stung."),
],
"gardening-decor": [
    ("White Pebbles — 1 kg", 249, "white pebbles stones", ["pebble"], "A clean mulch layer that hides soil and holds moisture."),
    ("Coloured Glass Pebbles — 500 g", 299, "glass pebbles decorative", ["pebble"], "Tumbled glass for terrariums and water bowls."),
    ("Moss Pole — 2 ft", 399, "moss pole plant support", ["moss"], "Gives a monstera or philodendron something to climb."),
    ("Wooden Plant Stand", 899, "wooden plant stand", ["stand"], "Raises a pot off a cold floor and into the light."),
    ("Metal Plant Stand — 3 Tier", 1299, "metal plant stand tiered", ["stand"], "Three levels of pots in the footprint of one."),
    ("Ceramic Pot Saucer — Set of 3", 299, "plant pot saucer tray", ["saucer"], "Catches the run-off so a floor or sill stays dry."),
    ("Garden Fairy Figurine", 349, "garden fairy figurine", ["figurine"], "A small resin figure for a pot corner or a fairy garden."),
    ("Wind Chime — Bamboo", 449, "bamboo wind chime", ["chime"], "Hollow bamboo notes for a balcony that catches the breeze."),
    ("Bird Bath — Terracotta", 799, "bird bath garden", ["bird"], "A shallow clay dish that brings sunbirds to a balcony."),
],
}

CATEGORIES = {
    "pots": ("Pots", "Terracotta, ceramic, hanging and self-watering pots.", "/images/category-pots.png"),
    "soil": ("Soil", "Potting mixes, cocopeat and the amendments that go with them.", "/images/category-soil.png"),
    "fertilisers": ("Fertilisers", "Organic and mineral feeds for leaf, root and bloom.", "/images/category-fertilisers.png"),
    "garden-tools": ("Garden Tools", "Trowels, pruners and the hand tools that outlast a season.", "/images/category-tools.png"),
    "watering-solutions": ("Watering Solutions", "Cans, sprayers, hoses and drip kits.", "/images/category-watering.png"),
    "pest-control": ("Pest Control", "Neem, traps and biologicals — nothing that needs a mask.", "/images/category-pest-control.png"),
    "gardening-decor": ("Gardening Decor", "Pebbles, stands, saucers and the small finishing touches.", "/images/category-decor.png"),
}
# fmt: on

# The Wikipedia article whose lead photograph shows the object itself. An
# article's lead image is chosen by editors to illustrate the thing, which is
# a far better product photo than anything a Commons keyword search returns.
ARTICLES: dict[str, str] = {
    "Terracotta Pot — 6 inch": "Flowerpot",
    "Terracotta Pot Set of 3": "Terracotta",
    "Glazed Ceramic Planter — 8 inch": "Flowerpot",
    "White Ceramic Pot with Saucer": "Flowerpot",
    "Hanging Basket with Chain": "Hanging basket",
    "Railing Planter — Balcony": "Window box",
    "Self-Watering Pot — 7 inch": "Self-watering container",
    "HDPE Grow Bag — Pack of 5": "Grow bag",
    "Nursery Plastic Pot — Pack of 10": "Plant nursery",
    "Woven Basket Planter": "Wicker",
    "All-Purpose Potting Mix — 5 kg": "Potting soil",
    "Cocopeat Block — 5 kg Expandable": "Coir",
    "Vermicompost — 5 kg": "Vermicompost",
    "Red Soil — 5 kg": "Laterite",
    "River Sand — 5 kg": "Sand",
    "Perlite — 1 kg": "Perlite",
    "Vermiculite — 1 kg": "Vermiculite",
    "Leaf Compost — 5 kg": "Compost",
    "Bone Meal — 1 kg": "Bone meal",
    "Neem Cake — 1 kg": "Azadirachta indica",
    "Mustard Cake Powder — 1 kg": "Mustard seed",
    "NPK 19:19:19 — 900 g": "Fertilizer",
    "Seaweed Extract — 500 ml": "Kelp",
    "Epsom Salt — 900 g": "Magnesium sulfate",
    "Organic Liquid Fertiliser — 500 ml": "Liquid fertilizer",
    "Rose & Flower Mix — 1 kg": "Fertilizer",
    "Humic Acid Granules — 500 g": "Humic substance",
    "Hand Trowel — Stainless Steel": "Trowel",
    "Hand Fork": "Garden fork",
    "Khurpi — Indian Weeding Hoe": "Hoe (tool)",
    "Pruning Secateurs": "Pruning shears",
    "Garden Scissors": "Scissors",
    "Hand Weeder": "Weeder",
    "Gardening Gloves": "Glove",
    "Garden Rake — Hand Size": "Rake (tool)",
    "5-Piece Garden Tool Set": "Garden tool",
    "Watering Can — 5 Litre": "Watering can",
    "Hand Mist Sprayer — 500 ml": "Spray bottle",
    "Pressure Sprayer — 2 Litre": "Sprayer",
    "Garden Hose — 15 m": "Garden hose",
    "Hose Spray Nozzle": "Spray nozzle",
    "Drip Irrigation Kit — 20 Plants": "Drip irrigation",
    "Rotating Sprinkler": "Irrigation sprinkler",
    "Self-Watering Spikes — Pack of 4": "Self-watering container",
    "Neem Oil — 250 ml": "Neem oil",
    "Yellow Sticky Traps — Pack of 10": "Insect trap",
    "Insecticidal Soap — 500 ml": "Soap",
    "Sulphur Powder — 500 g": "Sulfur",
    "Copper Fungicide — 250 g": "Bordeaux mixture",
    "Trichoderma Viride — 500 g": "Trichoderma",
    "Diatomaceous Earth — 500 g": "Diatomaceous earth",
    "Pheromone Fruit Fly Trap": "Insect trap",
    "White Pebbles — 1 kg": "Pebble",
    "Coloured Glass Pebbles — 500 g": "Sea glass",
    "Moss Pole — 2 ft": "Sphagnum",
    "Wooden Plant Stand": "Jardinière",
    "Metal Plant Stand — 3 Tier": "Étagère",
    "Ceramic Pot Saucer — Set of 3": "Saucer",
    "Garden Fairy Figurine": "Garden gnome",
    "Wind Chime — Bamboo": "Wind chime",
    "Bird Bath — Terracotta": "Bird bath",
}
